package main

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/dxui-org/dxui/internal/icondata"
)

func encodeIcon(box icondata.Rect, paths []icondata.Path) (string, error) {
	var result bytes.Buffer
	writeFloat := func(value float32) { _ = binary.Write(&result, binary.LittleEndian, math.Float32bits(value)) }
	writeFloat(box.X)
	writeFloat(box.Y)
	writeFloat(box.Width)
	writeFloat(box.Height)
	for _, path := range paths {
		if len(path.Commands) == 0 || len(path.Commands) > math.MaxUint16 {
			return "", fmt.Errorf("path command count %d is outside 1..65535", len(path.Commands))
		}
		result.WriteByte(byte(path.Mode))
		_ = binary.Write(&result, binary.LittleEndian, uint16(len(path.Commands)))
		for _, command := range path.Commands {
			result.WriteByte(byte(command.Verb))
			points := 0
			switch command.Verb {
			case icondata.PathMove, icondata.PathLine:
				points = 1
			case icondata.PathQuad:
				points = 2
			case icondata.PathCubic:
				points = 3
			case icondata.PathClose:
			default:
				return "", fmt.Errorf("unknown path verb %d", command.Verb)
			}
			for _, point := range command.Points[:points] {
				writeFloat(point.X)
				writeFloat(point.Y)
			}
		}
	}
	return result.String(), nil
}

func generate(iconDir, catalogDir, fixtureDir string, icons []sourceIcon, license string) error {
	if len(icons) == 0 {
		return fmt.Errorf("no icons")
	}
	functionBySlug, err := resolveNames(icons)
	if err != nil {
		return err
	}
	canonicalCount := 0
	for _, icon := range icons {
		if icon.canonical {
			canonicalCount++
		}
	}
	var source bytes.Buffer
	fmt.Fprintf(&source, "// Code generated by go generate; DO NOT EDIT.\n")
	fmt.Fprintf(&source, "// Lucide %s, commit %s, ISC/MIT; see LICENSE.\n\n", lucideVersion, lucideCommit)
	fmt.Fprintf(&source, "package icon\n\nimport \"github.com/dxui-org/dxui/internal/icondata\"\n\n")
	fmt.Fprintf(&source, "const Version = %q\nconst Count = %d\nconst CanonicalCount = %d\n\n", lucideVersion, len(icons), canonicalCount)
	for _, icon := range icons {
		name := functionBySlug[icon.slug]
		fmt.Fprintf(&source, "// %s returns the Lucide %q icon.\n", name, icon.slug)
		if icon.aliasOf != "" {
			fmt.Fprintf(&source, "func %s() icondata.Data { return %s() }\n\n", name, functionBySlug[icon.aliasOf])
		} else {
			fmt.Fprintf(&source, "func %s() icondata.Data {\n\tconst data = %s\n\treturn icondata.Packed(data)\n}\n\n", name, strconv.Quote(icon.encoded))
		}
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("format icon source: %w", err)
	}
	if err := os.MkdirAll(iconDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(iconDir, "icons_generated.go"), formatted, 0o644); err != nil {
		return err
	}
	packageSource := fmt.Sprintf("// Package icon provides the complete Lucide %s icon set as immutable dxui.IconData values.\n//\n// Generated functions allocate no memory and the Go linker can discard every unused icon.\n// StrokeWidth defaults to 2 icon view-box units and can be overridden through dxui.IconProps.\npackage icon\n\n//go:generate go run ../internal/cmd/lucidegen -source ../third_party/lucide/lucide-static-%s.tgz -out . -catalog catalog -fixtures ..\n", lucideVersion, lucideVersion)
	if err := os.WriteFile(filepath.Join(iconDir, "doc.go"), []byte(packageSource), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(iconDir, "LICENSE"), []byte(license), 0o644); err != nil {
		return err
	}
	if err := generateCatalog(catalogDir, icons, functionBySlug); err != nil {
		return err
	}
	return generateReferenceFixtures(fixtureDir, icons)
}

func generateReferenceFixtures(directory string, icons []sourceIcon) error {
	wanted := map[string]bool{"atom": true, "badge-cent": true, "brain-circuit": true, "search": true}
	var source bytes.Buffer
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage dxui\n\nimport \"github.com/dxui-org/dxui/internal/icondata\"\n\n")
	source.WriteString("var lucideReferenceIcons = map[string]IconData{\n")
	for _, value := range icons {
		if wanted[value.slug] {
			fmt.Fprintf(&source, "\t%q: icondata.Packed(%s),\n", value.slug, strconv.Quote(value.encoded))
			delete(wanted, value.slug)
		}
	}
	if len(wanted) != 0 {
		return fmt.Errorf("missing reference fixtures: %v", wanted)
	}
	source.WriteString("}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(directory, "icon_reference_generated_test.go"), formatted, 0o644)
}

func generateCatalog(directory string, icons []sourceIcon, functions map[string]string) error {
	var source bytes.Buffer
	source.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage catalog\n\nimport (\n\t\"github.com/dxui-org/dxui\"\n\t\"github.com/dxui-org/dxui/icon\"\n)\n\n")
	source.WriteString("// Entry maps a Lucide kebab-case name and Go constructor name to its lazy icon constructor.\ntype Entry struct {\n\tName string\n\tGoName string\n\tIcon func() dxui.IconData\n}\n\n")
	source.WriteString("// Icons contains all canonical icons and aliases. Importing catalog intentionally makes the full library reachable.\nvar Icons = []Entry{\n")
	for _, value := range icons {
		fmt.Fprintf(&source, "\t{Name: %q, GoName: %q, Icon: icon.%s},\n", value.slug, functions[value.slug], functions[value.slug])
	}
	source.WriteString("}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("format catalog: %w", err)
	}
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(directory, "catalog_generated.go"), formatted, 0o644)
}

func goName(slug string) string {
	return goNameWithNumericPrefix(slug, false)
}

func goNameWithNumericPrefix(slug string, prefixNumeric bool) string {
	parts := strings.FieldsFunc(slug, func(value rune) bool { return value == '-' || value == '_' || value == ' ' })
	var result strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		if prefixNumeric && unicode.IsDigit(runes[0]) {
			result.WriteRune('N')
		}
		result.WriteRune(unicode.ToUpper(runes[0]))
		result.WriteString(string(runes[1:]))
	}
	name := result.String()
	if name == "" || !unicode.IsLetter([]rune(name)[0]) {
		name = "Icon" + name
	}
	return name
}

func resolveNames(icons []sourceIcon) (map[string]string, error) {
	counts := make(map[string]int, len(icons))
	for _, icon := range icons {
		counts[goName(icon.slug)]++
	}
	result := make(map[string]string, len(icons))
	owners := make(map[string]string, len(icons))
	for _, icon := range icons {
		name := goName(icon.slug)
		if counts[name] > 1 {
			name = goNameWithNumericPrefix(icon.slug, true)
		}
		if owner := owners[name]; owner != "" {
			return nil, fmt.Errorf("Go name collision: %s and %s become %s", owner, icon.slug, name)
		}
		owners[name], result[icon.slug] = icon.slug, name
	}
	return result, nil
}

func sortedSlugs(icons []sourceIcon) []string {
	result := make([]string, len(icons))
	for index, icon := range icons {
		result[index] = icon.slug
	}
	sort.Strings(result)
	return result
}
